Smarter release ci stage

diff --git a/.github/workflows/telomare-ci.yml b/.github/workflows/telomare-ci.yml
--- a/.github/workflows/telomare-ci.yml
+++ b/.github/workflows/telomare-ci.yml
@@ -110,14 +110,29 @@ jobs:
         run: |
           ls
           cd telomare
-          nix develop -c cabal haddock --haddock-hyperlink-source
+          (nix develop -c cabal haddock --haddock-hyperlink-source) > ../haddock-output
           echo OK Haddock build
       - name: haddock copy
         run: |
           ls
+          # Check if the file exists
+          if [ ! -e haddock-output ]; then
+              echo "Error: File '$file_path' does not exist."
+              exit 1
+          fi
+
+          # Check if the file is empty
+          if [ ! -s haddock-output ]; then
+              echo "Error: File '$file_path' is empty."
+              exit 1
+          fi
+          current_dir=$(pwd)
+          # takes the last line of the haddock-output and removes overlapping paths with
+          # the current directory and also takes away the file name at the end of the path
+          doc_loc=$(tail -n 1 haddock-output | sed "s|^$current_dir/\(.*\)/.*|\1|")
           rm -rf stand-in-language.github.io/docs/haddock/
           mkdir stand-in-language.github.io/docs/haddock/
-          cp -r telomare/dist-newstyle/build/x86_64-linux/ghc-9.2.4/telomare-0.1.0.0/doc/html/telomare/. stand-in-language.github.io/docs/haddock
+          cp -r "$doc_loc"/. stand-in-language.github.io/docs/haddock
       - uses: EndBug/add-and-commit@v7
         with:
           message: 'haddock documentation automatically updated'
